#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of MainFrame1, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include
#include <wx\wxprec.h>
#include <wx\dcbuffer.h>

/** Implementing MainFrame1 */
class MainFrame : public MainFrame1
{
	protected:
		// Handlers for MainFrame1 events.
		void update( wxUpdateUIEvent& event );
		void draw( wxPaintEvent& event );
		void drawt(wxCommandEvent& event);
		void draw();
		void save_picture( wxCommandEvent& event );
		void give_monkey_banana( wxCommandEvent& event );
		void scrollbar_changed( wxScrollEvent& event );
		void text_updated( wxCommandEvent& event );
	public:
		/** Constructor */
		MainFrame( wxWindow* parent );
	//// end generated class members
	protected:
		bool save = false;





};

#endif // __MainFrame__
